### ISSUE TITLE
Unable to use with Mule 3.8.1

### ISSUE THREAD

**Issue by cthulu** [mulesoft/jira-connector#32]
When trying to connect to JIRA (7.0.10) from AnyPoint (Mule Runtime 3.8.1) I get the following exception when testing the connection:

```
java.lang.NoSuchMethodError: org.apache.http.impl.client.cache.CacheConfig.setNeverCache1_0ResponsesWithQueryString(Z)V
java.lang.NoSuchMethodError: org.apache.http.impl.client.cache.CacheConfig.setNeverCache1_0ResponsesWithQueryString(Z)V
    at com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClient.<init>(DefaultHttpClient.java:155)
    at com.atlassian.jira.rest.client.internal.async.AsynchronousHttpClientFactory.createClient(AsynchronousHttpClientFactory.java:53)
    at com.atlassian.jira.rest.client.internal.async.AsynchronousJiraRestClientFactory.create(AsynchronousJiraRestClientFactory.java:35)
    at com.atlassian.jira.rest.client.internal.async.AsynchronousJiraRestClientFactory.createWithBasicHttpAuthentication(AsynchronousJiraRestClientFactory.java:42)
    at org.mule.modules.jirarest.config.ConnectorConfig.connect(ConnectorConfig.java:82)
    at org.mule.modules.jirarest.connectivity.ConnectorConfigJiraRestConnectorAdapter.test(ConnectorConfigJiraRestConnectorAdapter.java:29)
    at org.mule.modules.jirarest.connectivity.JiraRestConnectorJirarestConnectionManagementConnectionManager.test(JiraRestConnectorJirarestConnectionManagementConnectionManager.java:388)
    at org.mule.tooling.metadata.api.utils.ConnectionTester.internalTestConnection(ConnectionTester.java:88)
    at org.mule.tooling.metadata.api.utils.ConnectionTester.testConnectionFor(ConnectionTester.java:113)
    at org.mule.tooling.messageflow.action.TestConnectorConnectionFromMuleConfigAction$1$1$1$1.call(TestConnectorConnectionFromMuleConfigAction.java:68)
    at org.mule.tooling.messageflow.action.TestConnectorConnectionFromMuleConfigAction$1$1$1$1.call(TestConnectorConnectionFromMuleConfigAction.java:1)
    at org.mule.tooling.utils.SilentRunner.run(SilentRunner.java:25)
    at org.mule.tooling.core.StudioDesignContextRunner.runSilentWithMuleProject(StudioDesignContextRunner.java:17)
    at org.mule.tooling.core.StudioDesignContextRunner.runSilentWithMuleProject(StudioDesignContextRunner.java:37)
    at org.mule.tooling.messageflow.action.TestConnectorConnectionFromMuleConfigAction$1$1$1.run(TestConnectorConnectionFromMuleConfigAction.java:65)
    at java.lang.Thread.run(Thread.java:745)

  java.lang.Throwable: java.lang.NoSuchMethodError: org.apache.http.impl.client.cache.CacheConfig.setNeverCache1_0ResponsesWithQueryString(Z)V
    at com.atlassian.httpclient.apache.httpcomponents.DefaultHttpClient.<init>(DefaultHttpClient.java:155)
    at com.atlassian.jira.rest.client.internal.async.AsynchronousHttpClientFactory.createClient(AsynchronousHttpClientFactory.java:53)
    at com.atlassian.jira.rest.client.internal.async.AsynchronousJiraRestClientFactory.create(AsynchronousJiraRestClientFactory.java:35)
    at com.atlassian.jira.rest.client.internal.async.AsynchronousJiraRestClientFactory.createWithBasicHttpAuthentication(AsynchronousJiraRestClientFactory.java:42)
    at org.mule.modules.jirarest.config.ConnectorConfig.connect(ConnectorConfig.java:82)
    at org.mule.modules.jirarest.connectivity.ConnectorConfigJiraRestConnectorAdapter.test(ConnectorConfigJiraRestConnectorAdapter.java:29)
    at org.mule.modules.jirarest.connectivity.JiraRestConnectorJirarestConnectionManagementConnectionManager.test(JiraRestConnectorJirarestConnectionManagementConnectionManager.java:388)
    at org.mule.tooling.metadata.api.utils.ConnectionTester.internalTestConnection(ConnectionTester.java:88)
    at org.mule.tooling.metadata.api.utils.ConnectionTester.testConnectionFor(ConnectionTester.java:113)
    at org.mule.tooling.messageflow.action.TestConnectorConnectionFromMuleConfigAction$1$1$1$1.call(TestConnectorConnectionFromMuleConfigAction.java:68)
    at org.mule.tooling.messageflow.action.TestConnectorConnectionFromMuleConfigAction$1$1$1$1.call(TestConnectorConnectionFromMuleConfigAction.java:1)
    at org.mule.tooling.utils.SilentRunner.run(SilentRunner.java:25)
    at org.mule.tooling.core.StudioDesignContextRunner.runSilentWithMuleProject(StudioDesignContextRunner.java:17)
    at org.mule.tooling.core.StudioDesignContextRunner.runSilentWithMuleProject(StudioDesignContextRunner.java:37)
    at org.mule.tooling.messageflow.action.TestConnectorConnectionFromMuleConfigAction$1$1$1.run(TestConnectorConnectionFromMuleConfigAction.java:65)
    at java.lang.Thread.run(Thread.java:745)

    at org.mule.tooling.metadata.utils.MetadataUtils.showErrorMessage(MetadataUtils.java:373)
    at org.mule.tooling.metadata.utils.MetadataUtils.showTestConnectionErrorMessage(MetadataUtils.java:338)
    at org.mule.tooling.messageflow.action.TestConnectorConnectionFromMuleConfigAction.displayResultMessage(TestConnectorConnectionFromMuleConfigAction.java:110)
    at org.mule.tooling.messageflow.action.TestConnectorConnectionFromMuleConfigAction.run(TestConnectorConnectionFromMuleConfigAction.java:98)
    at org.mule.tooling.messageflow.dialog.GlobalElementDialog$1.widgetSelected(GlobalElementDialog.java:404)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1499)
    at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1299)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
    at org.eclipse.jface.window.Window.runEventLoop(Window.java:827)
    at org.eclipse.jface.window.Window.open(Window.java:803)
    at org.mule.tooling.ui.modules.core.widgets.editors.GlobalRefEditor$1.run(GlobalRefEditor.java:596)
    at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
    at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
    at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
    at org.eclipse.jface.action.ActionContributionItem$6.handleEvent(ActionContributionItem.java:462)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1499)
    at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1299)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
```

**Comment by tonedef71** [comment]
I am having the same issue with hotovo.com's certified Jira REST connector using Mule EE Runtime v3.8.0.  The Mule EE Runtime v3.8.x bundles the httpclient-cache-4.4.1.jar library which clashes at runtime with the httpclient-cache-4.2.1-atlassian-2.jar library provided by the Jira REST connector.  The setNeverCache1_0ResponsesWithQueryString(boolean):void method of the CacheConfig class does not exist in the CacheConfig class of the standard httpclient-cache-4.4.1.jar library, hence the NoSuchMethodException.  The httpclient-cache-4.4.1.jar libarary takes precedence over the httpclient-cache-4.2.1-atlassian-2.jar library in the runtime classpath.

**Update:**  I have opened a Jira ticket with hotovo: https://hotovo.jira.com/servicedesk/customer/portal/2/MC-17

**Comment by frappierer** [comment]
Was someone able to find a solution?

Cheers 
Martin

**Comment by tonedef71** [comment]
@frappierer After posting a ticket to Hotovo's JIRA, I received the following reply from a Hotovo staff member on 10/20/2016: 

> We also noticed this dependency issue when using 3.8 runtime and we are currently working on it. New version of connector should be published in a ~ month, after it'll pass certification process. I will contact you as soon as I get more information.

As of today, I have still not been notified by Hotovo regarding a fixed version of the Jira REST connector; perhaps the certification process is a lengthy ordeal.

**Comment by frappierer** [comment]
@tonedef71 
Thx.
Sorry for my late response. I will get in touch with them as well.
